// Demo recipes for the Rivera family. `art` describes the generated illustration (null = no photo).
// Ingredient tuples: [quantity|null, unit|null, name, note?]

export const SEED_RECIPES = [
  {
    key: 'pasta',
    title: 'Creamy Tomato Basil Pasta',
    description: 'Our weeknight hero: a silky tomato cream sauce that clings to every noodle. Ready before anyone asks "what\'s for dinner?" twice.',
    servings: 4, prep: 10, cook: 20, icon: 'utensils', color: '#E5484D',
    tags: ['dinner', 'kid-friendly', 'vegetarian', 'quick'], by: 'sam', favs: ['mia', 'leo', 'sam'],
    art: { kind: 'pasta', table: '#e8d6bf', cloth: '#5b5bd6' },
    ingredients: [
      [400, 'g', 'penne pasta'], [2, 'tbsp', 'olive oil'], [3, 'clove', 'garlic', 'minced'], [1, 'can', 'crushed tomatoes', '400 g'],
      [0.5, 'cup', 'heavy cream'], [0.5, 'cup', 'parmesan', 'grated'], [1, 'handful', 'fresh basil'], [null, null, 'salt and black pepper'],
    ],
    steps: [
      'Bring a big pot of well-salted water to a boil and cook the penne 1 minute less than the package says. Save a mug of pasta water.',
      'Meanwhile warm the olive oil in a wide pan over medium heat. Add the garlic and cook for 1 minute until fragrant — don\'t let it brown.',
      'Pour in the crushed tomatoes, season with salt and pepper and simmer for 10 minutes, stirring now and then.',
      'Stir in the cream and parmesan. Add the drained pasta and a splash of pasta water; toss until glossy.',
      'Tear the basil over the top and serve with extra parmesan at the table.',
    ],
  },
  {
    key: 'salmon',
    title: 'Sheet-Pan Lemon Herb Salmon',
    description: 'Salmon, asparagus and baby potatoes roasted on one tray. Bright, healthy, and only one pan to wash.',
    servings: 4, prep: 10, cook: 25, icon: 'fish', color: '#0090FF',
    tags: ['dinner', 'healthy', 'gluten-free', 'one-pan'], by: 'sam', favs: ['sam', 'alex'],
    art: { kind: 'salmon', table: '#d9e2e6', cloth: '#12a594' },
    ingredients: [
      [4, null, 'salmon fillets'], [500, 'g', 'baby potatoes', 'halved'], [1, 'bunch', 'asparagus'], [1, null, 'lemon'],
      [3, 'tbsp', 'olive oil'], [2, 'clove', 'garlic'], [1, 'tbsp', 'fresh dill'], [null, null, 'salt and black pepper'],
    ],
    steps: [
      'Heat the oven to 220°C / 425°F. Toss the potatoes with 1 tbsp oil, salt and pepper and roast for 12 minutes.',
      'Push the potatoes to the sides. Add the asparagus and salmon to the tray.',
      'Mix the remaining oil with grated garlic, lemon zest and dill; brush over the salmon and asparagus.',
      'Roast for 12–14 minutes until the salmon flakes easily.',
      'Squeeze lemon juice over everything and serve straight from the pan.',
    ],
  },
  {
    key: 'tacos',
    title: 'Taco Tuesday Chicken Tacos',
    description: 'Smoky, juicy chicken with all the toppings laid out so everyone builds their own. A Rivera tradition.',
    servings: 4, prep: 15, cook: 20, icon: 'drumstick', color: '#F76B15',
    tags: ['dinner', 'kid-friendly', 'mexican', 'family favorite'], by: 'alex', favs: ['leo', 'mia', 'alex'],
    art: { kind: 'tacos', table: '#f0dcc4', cloth: '#e5484d' },
    ingredients: [
      [600, 'g', 'chicken thighs', 'boneless'], [2, 'tsp', 'smoked paprika'], [1, 'tsp', 'cumin'], [1, 'tbsp', 'olive oil'],
      [8, null, 'small tortillas'], [2, null, 'tomatoes', 'diced'], [1, null, 'avocado'], [1, 'cup', 'shredded lettuce'],
      [0.5, 'cup', 'sour cream'], [1, null, 'lime'], [1, 'cup', 'cheddar', 'grated'],
    ],
    steps: [
      'Rub the chicken with paprika, cumin, oil and a good pinch of salt.',
      'Cook in a hot skillet for 6–7 minutes per side until charred and cooked through. Rest for 5 minutes, then slice.',
      'Warm the tortillas in a dry pan for 30 seconds per side and keep them wrapped in a towel.',
      'Set out tomatoes, avocado, lettuce, cheese, sour cream and lime wedges.',
      'Build your own tacos at the table!',
    ],
  },
  {
    key: 'pancakes',
    title: 'Fluffy Blueberry Pancakes',
    description: 'Tall, tender buttermilk pancakes studded with blueberries. The official Saturday-morning breakfast.',
    servings: 4, prep: 10, cook: 15, icon: 'egg', color: '#8E4EC6',
    tags: ['breakfast', 'weekend', 'kid-friendly', 'vegetarian'], by: 'mia', favs: ['mia', 'leo', 'alex', 'sam'],
    art: { kind: 'pancakes', table: '#efe3d0', cloth: '#ffb224' },
    ingredients: [
      [2, 'cup', 'flour'], [2, 'tbsp', 'sugar'], [2, 'tsp', 'baking powder'], [0.5, 'tsp', 'salt'], [1.5, 'cup', 'milk'],
      [2, null, 'eggs'], [3, 'tbsp', 'butter', 'melted'], [1, 'cup', 'blueberries'], [null, null, 'maple syrup', 'to serve'],
    ],
    steps: [
      'Whisk the flour, sugar, baking powder and salt in a large bowl.',
      'In another bowl whisk milk, eggs and melted butter. Pour into the dry ingredients and stir just until combined — lumps are fine!',
      'Let the batter rest for 5 minutes while the pan heats over medium-low.',
      'Pour ¼ cup of batter per pancake, scatter with blueberries and cook until bubbles appear, about 2 minutes. Flip and cook 1 minute more.',
      'Stack high and drizzle with maple syrup.',
    ],
  },
  {
    key: 'salad',
    title: 'Greek Salad with Feta',
    description: 'Crunchy cucumber, sweet tomatoes, olives and creamy feta with a lemony oregano dressing.',
    servings: 4, prep: 15, cook: 0, icon: 'salad', color: '#30A46C',
    tags: ['lunch', 'vegetarian', 'quick', 'healthy'], by: 'sam', favs: ['sam'],
    art: { kind: 'salad', table: '#e2e6dc', cloth: '#0090ff' },
    ingredients: [
      [1, 'head', 'romaine lettuce'], [1, null, 'cucumber'], [250, 'g', 'cherry tomatoes'], [0.5, null, 'red onion'],
      [100, 'g', 'kalamata olives'], [200, 'g', 'feta'], [3, 'tbsp', 'olive oil'], [1, null, 'lemon'], [1, 'tsp', 'dried oregano'],
    ],
    steps: [
      'Chop the lettuce and cucumber, halve the tomatoes and thinly slice the red onion.',
      'Whisk the olive oil, lemon juice, oregano and a pinch of salt.',
      'Toss the vegetables and olives with the dressing.',
      'Crumble the feta on top just before serving.',
    ],
  },
  {
    key: 'curry',
    title: 'Coconut Chicken Curry',
    description: 'A gentle, fragrant curry the whole family can handle — add chili on the side for the grown-ups. Even better the next day.',
    servings: 6, prep: 15, cook: 35, icon: 'soup', color: '#FFB224',
    tags: ['dinner', 'batch cook', 'gluten-free'], by: 'alex', favs: ['alex', 'sam'],
    art: { kind: 'bowl', table: '#e6d5c3', cloth: '#30a46c', sauce: '#e39b2e', chunk: '#f5dcb4', veg: '#30a46c' },
    ingredients: [
      [800, 'g', 'chicken thighs'], [1, null, 'onion'], [3, 'clove', 'garlic'], [1, 'tbsp', 'fresh ginger', 'grated'],
      [3, 'tbsp', 'mild curry paste'], [1, 'can', 'coconut milk', '400 ml'], [1, 'can', 'chopped tomatoes'],
      [2, 'cup', 'spinach'], [2, 'cup', 'basmati rice'], [1, 'handful', 'cilantro'],
    ],
    steps: [
      'Start the rice according to the package.',
      'Soften the chopped onion in a little oil for 5 minutes. Add garlic, ginger and curry paste and cook for 1 minute.',
      'Add the chicken pieces and stir until coated. Pour in the coconut milk and tomatoes.',
      'Simmer gently for 25 minutes until the chicken is tender and the sauce has thickened.',
      'Stir in the spinach until wilted. Serve over rice with cilantro.',
    ],
  },
  {
    key: 'pizza',
    title: 'Homemade Margherita Pizza',
    description: 'Friday pizza night! Everyone stretches their own dough and picks their toppings.',
    servings: 4, prep: 90, cook: 12, icon: 'pizza', color: '#D6409F',
    tags: ['dinner', 'weekend', 'kid-friendly', 'family favorite', 'vegetarian'], by: 'leo', favs: ['leo', 'mia'],
    art: { kind: 'pizza', table: '#e3d2bd', cloth: '#d6409f' },
    ingredients: [
      [500, 'g', 'bread flour'], [7, 'g', 'dried yeast'], [325, 'ml', 'warm water'], [1, 'tsp', 'salt'], [2, 'tbsp', 'olive oil'],
      [1, 'cup', 'passata'], [250, 'g', 'mozzarella'], [1, 'handful', 'fresh basil'],
    ],
    steps: [
      'Mix flour, yeast and salt. Add the warm water and oil and knead for 10 minutes until smooth and springy.',
      'Cover and let the dough rise for 1 hour, until doubled.',
      'Heat the oven as hot as it goes (250°C / 480°F) with a tray inside.',
      'Divide the dough into 4 and stretch each into a thin round. Spread with passata and top with torn mozzarella.',
      'Bake for 10–12 minutes until bubbling and golden. Scatter basil and slice.',
    ],
  },
  {
    key: 'stirfry',
    title: 'Veggie Noodle Stir-Fry',
    description: 'Crisp vegetables and chewy noodles in a sticky soy-honey sauce. Ten minutes in the wok.',
    servings: 4, prep: 15, cook: 10, icon: 'cooking-pot', color: '#12A594',
    tags: ['dinner', 'vegetarian', 'quick'], by: 'alex', favs: ['alex'],
    art: { kind: 'stirfry', table: '#d8dde3', cloth: '#f76b15' },
    ingredients: [
      [300, 'g', 'egg noodles'], [1, null, 'red bell pepper'], [1, null, 'carrot'], [1, 'head', 'broccoli'], [2, null, 'spring onions'],
      [3, 'tbsp', 'soy sauce'], [1, 'tbsp', 'honey'], [1, 'tbsp', 'sesame oil'], [2, 'clove', 'garlic'], [1, 'tbsp', 'sesame seeds'],
    ],
    steps: [
      'Cook the noodles, drain and toss with a little sesame oil.',
      'Whisk soy sauce, honey and minced garlic together.',
      'Stir-fry the broccoli, pepper and carrot in a very hot wok for 4 minutes.',
      'Add the noodles and sauce and toss for 2 minutes until glossy.',
      'Top with spring onions and sesame seeds.',
    ],
  },
  {
    key: 'oats',
    title: 'Overnight Oats',
    description: 'Five minutes the night before = a calm morning. Set up a jar for everyone with their favorite toppings.',
    servings: 4, prep: 5, cook: 0, icon: 'wheat', color: '#978365',
    tags: ['breakfast', 'make-ahead', 'healthy', 'vegetarian'], by: 'sam', favs: ['sam'],
    art: null,
    ingredients: [
      [2, 'cup', 'rolled oats'], [2, 'cup', 'milk'], [1, 'cup', 'greek yogurt'], [2, 'tbsp', 'chia seeds'],
      [2, 'tbsp', 'honey'], [1, 'cup', 'mixed berries'],
    ],
    steps: [
      'Stir oats, milk, yogurt, chia and honey together.',
      'Divide between 4 jars, cover and refrigerate overnight.',
      'In the morning top with berries (and a spoon of peanut butter for Leo).',
    ],
  },
  {
    key: 'banana',
    title: 'Banana Bread',
    description: 'The best use for those spotty bananas. Perfect for lunchboxes and after-school snacks.',
    servings: 10, prep: 15, cook: 55, icon: 'cake', color: '#FFB224',
    tags: ['snack', 'baking', 'kid-friendly'], by: 'mia', favs: ['mia', 'leo'],
    art: null,
    ingredients: [
      [3, null, 'ripe bananas'], [80, 'g', 'butter', 'melted'], [150, 'g', 'brown sugar'], [1, null, 'egg'],
      [1, 'tsp', 'vanilla extract'], [1, 'tsp', 'baking soda'], [190, 'g', 'flour'], [0.5, 'cup', 'chocolate chips', 'optional'],
    ],
    steps: [
      'Heat the oven to 175°C / 350°F and line a loaf tin.',
      'Mash the bananas, then mix in the butter, sugar, egg and vanilla.',
      'Fold in the baking soda, a pinch of salt and the flour. Add chocolate chips if you like.',
      'Pour into the tin and bake for 50–55 minutes until a skewer comes out clean.',
      'Cool for 10 minutes before slicing.',
    ],
  },
];

/**
 * The week plan relative to Monday (day 0..6). [day, slot, recipeKey | { title }, cook?, note?]
 */
export const SEED_THIS_WEEK = [
  [0, 'dinner', 'pasta', 'sam'],
  [0, 'breakfast', 'oats', null],
  [1, 'dinner', 'tacos', 'alex', 'Taco Tuesday!'],
  [1, 'lunch', { title: 'Leftover pasta' }, null],
  [2, 'dinner', 'curry', 'alex', 'Make a double batch for Thursday lunch'],
  [2, 'snack', 'banana', 'mia'],
  [3, 'dinner', 'salmon', 'sam'],
  [3, 'lunch', { title: 'Leftover curry' }, null],
  [4, 'dinner', 'pizza', 'leo', 'Pizza night — everyone makes their own'],
  [4, 'lunch', 'salad', 'sam'],
  [5, 'breakfast', 'pancakes', 'mia'],
  [5, 'lunch', { title: 'Picnic at the park' }, null, 'Sandwiches, fruit, lemonade'],
  [5, 'dinner', 'stirfry', 'alex'],
  [6, 'breakfast', 'pancakes', 'alex'],
  [6, 'dinner', { title: "Grandma's for Sunday roast" }, null],
  [6, 'snack', { title: 'Fruit skewers' }, 'leo'],
];

export const SEED_LAST_WEEK = [
  [0, 'dinner', 'stirfry', 'alex'],
  [1, 'dinner', 'tacos', 'alex'],
  [2, 'dinner', 'salmon', 'sam'],
  [3, 'dinner', { title: 'Soccer night — takeout' }, null],
  [4, 'dinner', 'pizza', 'leo'],
  [5, 'breakfast', 'pancakes', 'mia'],
  [5, 'dinner', 'curry', 'alex'],
  [6, 'breakfast', 'oats', 'sam'],
  [6, 'dinner', 'pasta', 'sam'],
  [2, 'lunch', 'salad', 'sam'],
];
